### ISSUE TITLE
Bounce on edge between two touching cubes

### ISSUE THREAD

**Issue by nem0** [jrouwe/JoltPhysics#717]
Steps to reproduce:
1. create two touching, static cubes with half extents =1
2. create dynamic sphere with radius == 0.1 on top of one of the cubes 
![image](https://github.com/jrouwe/JoltPhysics/assets/153526/db0c9a15-2f55-4827-8e14-d5871b232a3d)
3. set velocity of the sphere to {5, 0, 0}
4. run it
5. observe that the sphere bounces up on the edge between the cubes
![bounce](https://github.com/jrouwe/JoltPhysics/assets/153526/4d187bd9-5944-4214-aeb5-22ad812e454e)

Expected result:
ball should not bounce on flat surface

**Comment by jrouwe** [comment]
What convex radius did you use? With the default convex radius the collision of the boxes will actually look like this:

![image](https://github.com/jrouwe/JoltPhysics/assets/1621693/f98dec46-d85f-4c16-9b29-f9bf39fbc632)

So there will be a gap between the two boxes.

That said, Jolt doesn't currently do 'contact welding' between different objects, meaning that even though you do not see an edge here, there is one and the sphere can collide with it.

Note that this bug is very similar to https://github.com/godot-jolt/godot-jolt/issues/587 so you can look there for some more parameters you can tweak.

In any case, this is an area that I will be working on.

**Comment by mihe** [comment]
> Note that this bug is very similar to [godot-jolt/godot-jolt#587](https://github.com/godot-jolt/godot-jolt/issues/587) so you can look there for some more parameters you can tweak.

Just to avoid any confusion, since I took some creative liberties when naming some of those settings, the settings [highlighted](https://github.com/godot-jolt/godot-jolt/issues/587#issuecomment-1722556717) in that issue are (in order) `PhysicsSettings::mLinearCastThreshold`, `PhysicsSettings::mSpeculativeContactDistance` and `PhysicsSettings::mPenetrationSlop`.

**Comment by nem0** [comment]
> What convex radius did you use? With the default convex radius the collision of the boxes will actually look like this:

Default radius. Also tried with different values, both smaller and bigger, results were even worse. 

Tweaking values from https://github.com/godot-jolt/godot-jolt/issues/587 helped a bit, but it's still not perfect

**Comment by jrouwe** [comment]
Hello,

I submitted a potential fix for this issue (set BodyCreationSettings::mEnhancedInternalEdgeRemoval = true). I wrote some documentation for this new functionality [here](https://jrouwe.github.io/JoltPhysics/#ghost-collisions).

Please note that you'll have to make your boxes be part of the same body or else the algorithm will not work. Because of the way Jolt multithreads collision detection, collisions between different body pairs run on different threads, so it is very difficult to make this algorithm work across bodies.

**Comment by jrouwe** [comment]
I also posted a video of the results here: https://x.com/jrouwe/status/1748821475623088550?s=20

**Comment by afritz1** [comment]
Just double checking before I attempt this. I have a Minecraft-like world and my Character capsule is hopping erratically across the ground when moving which I don't want. If I put all box colliders in a MutableCompoundShape with `mEnhancedInternalEdgeRemoval` then it should fix this?

In theory if I make the compound shape encapsulate 3x3 chunks (192x192 voxels), the player will never hiccup crossing a chunk edge. I think I'll have to combine voxels because I've gone past 100k box colliders and that feels a little crazy, although performance is fine since they're all static.

**Comment by jrouwe** [comment]
So if I understand correctly you plan to have:

* Single body for the static world
* Body has MutableCompoundShape has 3x3 chunks of StaticCompoundShape has 192x192 voxels of BoxShape
* You're constantly swapping out chunks in the MutableCompoundShape as the player moves

If so, then yes that should work with `mEnhancedInternalEdgeRemoval` to get rid of any collisions with edges.

**Comment by afritz1** [comment]
I didn't think of a compound shape of compound shapes, I'll try that, thank you. I'm glad I don't need to use a mesh collider for the ground.

**Comment by nem0** [comment]
Is mEnhancedInternalEdgeRemoval  suppose to work with meshes too? It fixed the issue with boxes, but I still get ghost collisions with meshes. 

https://github.com/user-attachments/assets/6775f7d0-b5f5-4e6b-be6e-c74baa397078

**Comment by jrouwe** [comment]
If I look at where the issue happens then at all spots the mesh looks very suspicious to me:

<img width="1796" height="802" alt="Image" src="https://github.com/user-attachments/assets/716829f9-b400-434a-9d4e-7cf8924a7e02" />

In the areas I marked, you see places where triangles look to be overlapping (double edges / crosses are usually not manifold). If I look at Kenny's asset:

<img width="1271" height="980" alt="Image" src="https://github.com/user-attachments/assets/742c7472-6b60-4e95-b58e-3769a3372d30" />

then it's really clean and doesn't have those double edges / crosses.

**Comment by jrouwe** [comment]
Ok, in that case I'll need something to reproduce this. If you can provide me with:

* A snapshot (see [here](https://github.com/jrouwe/JoltPhysics/blob/475e564ae87c1ff8cbeaca6a5659b110a1b29143/Samples/SamplesApp.cpp#L853-L864))
* If you're running Jolt in single or double precision
* Which version of Jolt you're running (tag or commit hash)

The snapshot would preferably be made while the ball is rolling but before it crosses the edges.
